### ISSUE TITLE
Minor tweaks

### ISSUE THREAD

**Issue by coatless** [produnis/hsnr-revealjs#1]
@produnis I'm going to respond over here instead of on our [PR discussion](https://github.com/coatless-quarto/hsnr-revealjs/pull/2) if that's okay. 

A few quick thoughts:

1. I would avoid nesting a folder inside of `_extensions`. 
    - So, I would suggest making the content of `HSNRThemes` be inline with `_extensions.yml`
2. I'm hesitant to include a `.bib` file inside of the theme.
    - I would suggest this as a feature of the template rollout.
3. The `quarto-timer` extension needs to be installed correctly for the theme: 

```
_extensions/
   |- _extensions/produnis/quarto-timer
```

4. `footer` should be under `hsnr-revealjs`

```md
---
author:
  - name: Your Name
    orcid: 0000-0000-0000-0000
    email: alias@email.com
    affiliations: Your Institution
date: last-modified
format:
  hsnr-revealjs:
    footer: "Prof. Dr. Theo Rethisch | Fachbereich 10 | Hochschule Niederrhein"
---

```

**Comment by produnis** [comment]
Hi there and thx for your suggestions. I removed the subfolder and put the bib-file into the main folder, where users can modify it. 
For now, I think I will go with the timer being included in the theme (while having a stand-alone-extension for the timer as well).
